//FibonnaciiSeries.Fibonacci();
//Console.WriteLine();
//PerfectNumber.PerfectNumber1();
//Console.WriteLine();
//PrimeNumber.PrimeNumber1();
//Console.WriteLine();
//ReverseNumber.ReverseNumber1();
//Console.WriteLine();
//CouponNumber.CouponNumber1();
//Stopwatch.Stopwatch1();
//Notes.Notes1();
//Util.dayOfWeek(1, 13, 2022);
//Util.temperatureConversion();
//Util.monthlyPayment(20000, 2, 25);
//Binary.toBinary(146);
//Sqrt.squareRoot();
